### ISSUE TITLE
Bug in inventory.js

### ISSUE THREAD

**Issue by alex-arkhipov** [Hydrotoast/Avaku#2]
Hello, it seems you have a bug in the following code:
Avaku.bindItemHandlers(
            algo.getByClass(config.ITEM_CLASS), elem);

One bracket is not in place. It should be like this:
Avaku.bindItemHandlers(
            algo.getByClass(config.ITEM_CLASS, elem));

**Comment by Hydrotoast** [comment]
Hello Alex,

The code you have highlighted is correct. Simply match the parentheses starting with the outer parantheses:

`Avaku.bindItemHandlers( ... );`

Then the inner parantheses:

`algo.getByClass(config.ITEM_CLASS), ...`

If you are receiving a syntax error upon usage, could you post the exact error here?

**Comment by alex-arkhipov** [comment]
Let me diasgree with you. Let's extend the code:
        elem.innerHTML = equippedHtml;
        Avaku.bindItemHandlers(algo.getByClass(config.ITEM_CLASS), elem);

This is function printEquipped. So, the handlers must be binded to equipped items only, rigth? To make this work, it is necessary to pass elem in getByClass as second parameter - parent. Otherwise, currently getByClass uses document as parent so return all ITEM_CLASS elements.
I am playing with your code a litle and get the situation when 2 handlers have been binded to unequipped items due to this code.
So, i have changed it like this:
        elem.innerHTML = equippedHtml;
        Avaku.bindItemHandlers(algo.getByClass(config.ITEM_CLASS, elem), true);
I do beleive it is more robust and correct. Sorry, if I seem to be rude. No bad feeling - just a note for you.

I appreciate your work on this project - it is amazing.

**Comment by Hydrotoast** [comment]
You were correct. `elem` should have originally been a parameter for `algo.getByClass`. Thanks for pointing out the issue.
