### ISSUE TITLE
Issue in avaku.js

### ISSUE THREAD

**Issue by alex-arkhipov** [Hydrotoast/Avaku#3]
Hello, this is another thing I have found.

It seems that "Clear" button doesn't work as expected. This is due to the following:
        clear.addEventListener('click', function() {
            for (var i in items) {
                var image = algo.getByClass(config.LAYER_CLASS, items[i])[0].firstChild;
                if (image != null && image.className.indexOf(config.EQUIPPED_CLASS) != -1) {
                    image.className = '';
                    avaku.avatar.removeLayer(image.getAttribute('data-src'));

```
                algo.getByClass(config.REMOVE_CLASS, items[i])[0].style.display = 'none';
            }
            avaku.draw();
        }
        return false;
    });
```

This code gets me an erorr that "items" is not defined. So, no code is executed after that.

**Comment by Hydrotoast** [comment]
You should consider submitting patches to contribute to the project since you seem to know the code fairly well.
